### ISSUE TITLE
addTodo isn't pure 

### ISSUE THREAD

**Issue by abdhalees** [facg3/SSST-T0DoList#18]
It's right that concat returns a new array and doesn't affect the original array, but you are affecting the objects of the array, here come's the use of ```cloneArrayOfObjects``` function which will return a new array with new objects. 
To avoid affecting global variables, test them after testing the function. 
https://github.com/facg3/SSST-T0DoList/blob/ff2031e129f1e3692be476dbed93cf7c94543f33/logic.js#L24

**Comment by ZooeyMiller** [comment]
As an added note to this, none of your functions use `cloneArrayOfObjects`, which is necessary to make your functions pure.

Even if you don't alter the original array, by using array methods which return a new array, you will alter the objects in the original array if you don't clone them. This is why `cloneArrayOfObjects` is provided.

**Comment by Salam-Dalloul** [comment]
it's pure now :D
