### ISSUE TITLE
ID isn't unique

### ISSUE THREAD

**Issue by abdhalees** [facg3/SSST-T0DoList#19]
When I mark or delete the first TODO I've added it also marks or deletes the initial TODO ```one``` 
that's because in your initial state you're giving the TODO an ID on 1, and in the ```genrateID``` function it starts from 1 also, so you will have to TODO's with the same ID. 
https://github.com/facg3/SSST-T0DoList/blob/ff2031e129f1e3692be476dbed93cf7c94543f33/dom.js#L4

**Comment by sultanassi95** [comment]
Got it.
