### ISSUE TITLE
Use classList functions

### ISSUE THREAD

**Issue by abdhalees** [facg3/SSST-T0DoList#20]
It's working well, but instead of checking with an if statement to add or remove use the function ```toggle``` in (classList)[https://developer.mozilla.org/en-US/docs/Web/API/Element/classList] to toggle between adding and removing a style. so you don't need two classes and you'll need just a line of code to do it.
https://github.com/facg3/SSST-T0DoList/blob/ff2031e129f1e3692be476dbed93cf7c94543f33/dom.js#L29

**Comment by sultanassi95** [comment]
DONE <3
