### ISSUE TITLE
separate your tests

### ISSUE THREAD

**Issue by abdhalees** [facg3/SSST-T0DoList#24]
Each test should test a function/request and that will be specified in the first argument in the tape function as a string.
So each function should be in  a different test function.  
https://github.com/facg3/SSST-T0DoList/blob/ff2031e129f1e3692be476dbed93cf7c94543f33/test.js#L4

**Comment by tqazaz** [comment]
Test Seperated Now ... thanks

**Comment by tqazaz** [comment]
__
